config/routes.rb
Plotbunnyshare::Application.routes.draw do
  devise_for :users
  root 'ideas#index'

  resources :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ideas 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def index
		@ideas = Idea.all
	end

	def new
		@idea = Idea.new
	end

	def create
		current_user.ideas.create(idea_params)
		redirect_to root_path
	end

	def edit 
		@idea = Idea.find(params[:id])
	end

	def show 
		@idea = Idea.find(params[:id])
	end

	def update
		@idea = Idea.find(params[:id])
		@idea.update_attributes(idea_params)
		redirect_to root_path
	end

	def destroy
		@idea = Idea.find(params[:id])
		@idea.destroy
		redirect_to root_path
	end

	private

	def idea_params
		params.require(:idea).permit(:title, :plot, :character, :setting, :notes)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/edit.html.erb
<div class="clear"></div>
<h1>Edit Your Idea</h1>
<%= simple_form_for @idea do |f| %>
	<%= f.input :title %>
	<br />
	<%= f.input :plot %>
	<br />
	<%= f.input :character %>
	<br />
	<%= f.input :setting %>
	<br />
	<%= f.input :notes %>
	<br />
	<%= f.submit 'Save', :class => 'btn btn-info' %>
<% end %>

app/views/ideas/index.html.erb
<% @ideas.each do |idea| %>
	<div class="clear"></div>
		<h3><%= link_to idea.title, idea_path(idea) %></h3><br />
		<%= idea.title %><br /><br />

		<h3>PLOT:</h3><br />
		<%= idea.plot %><br /><br />

		<h3>CHARACTERS:</h3><br />
		<%= idea.character %><br /><br />

		<h3>SETTING:</h3><br />
		<%= idea.setting %><br /><br />

		<h3>NOTES:</h3><br />
		<%= idea.notes %><br /><br />

		<% if idea.user.present? %> 
		<small><%= idea.user.email %></small>
		<% end %> 
	<hr />
<% end %>

app/views/ideas/new.html.erb
<h1>Enter Your Story Idea Details</h1>
<%= simple_form_for @idea do |f| %>
	<%= f.input :title %>
	<br />
	<%= f.input :plot %>
	<br />
	<%= f.input :character %>
	<br />
	<%= f.input :setting %>
	<br />
	<%= f.input :notes %>
	<br />
	<%= f.submit 'Create', :class => 'btn btn-info' %>
<% end %>

app/views/ideas/show.html.erb
<div class="clear"></div>
<br />
<br />

<h1><%= @idea.title %></h1><br /><br />

<h2>PLOT</h2><br />
<p><%= @idea.plot %></p><br />

<h2>CHARACTERS</h2><br />
<p><%= @idea.character %></p><br />

<h2>SETTING</h2><br />
<p><%= @idea.setting %></p><br />

<h2>NOTES</h2><br />
<p><%= @idea.notes %></p><br />

<div class="pull-right">
<%= link_to 'Edit', edit_idea_path(@idea), :class => 'btn btn-primary' %>

<%= link_to 'Destroy', idea_path(@idea), :method => :delete, :data => {:confirm => "Are you sure you want to delete this?"}, :class => 'btn btn-danger' %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plotbunnyshare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<!--Navigation Bar-->
			

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Plot Bunny Share</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
        	<%= link_to 'New Idea', new_idea_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
      		<li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      		<% else %>
      		<li><%= link_to 'Log In', new_user_session_path %></li>
      		<li><%= link_to 'Sign Up', new_user_registration_path %></li>
      		<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
<p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
<p class="alert alert-danger"><%= alert %></p>
<% end %> 



<%= yield %>

</body>
</html>